name: movies_streams
description: Project aimed at explaining Streams and BLoC.
author: Didier Boelens <mail@didierboelens.com>

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+1
  collection: ^1.14.11
  cupertino_icons: ^0.1.2
  rxdart: ^0.18.1
  flutter_range_slider: ^0.0.4
  tuple: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

flutter:
  uses-material-design: true

